// Code generated by go-swagger; DO NOT EDIT.

// Package restapi 5 Verst API
//
//  5Verst - application for plans the new running events.
//
//  ### Steps to start working with 5Verst API
//  1. Post the suggest about new events.
//  2. Get Get the list of suggested events with weather predictions.
//
//  ### Groups of Methods
//  * **Events** for create new events or get the list of events.
//
//  ****
//
//  Find more information
//  * about the 5Verst [5verst.ru](https://5verst.ru/)
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: v2-go
//  Contact: <info@5verst.ru>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
