// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ErrorUnprocessableEntity ErrorUnprocessableEntity
//
// swagger:model errorUnprocessableEntity
type ErrorUnprocessableEntity struct {

	// HTTP status code.
	// Required: true
	Code int32 `json:"code"`

	// Error message.
	// Required: true
	Message string `json:"message"`
}

// Validate validates this error unprocessable entity
func (m *ErrorUnprocessableEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorUnprocessableEntity) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", int32(m.Code)); err != nil {
		return err
	}

	return nil
}

func (m *ErrorUnprocessableEntity) validateMessage(formats strfmt.Registry) error {

	if err := validate.RequiredString("message", "body", string(m.Message)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ErrorUnprocessableEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorUnprocessableEntity) UnmarshalBinary(b []byte) error {
	var res ErrorUnprocessableEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
