// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Index Index
//
// swagger:model index
type Index struct {

	// Commit ID
	Commit string `json:"commit,omitempty"`

	// API build date.
	Date string `json:"date,omitempty"`

	// API description
	Info string `json:"info,omitempty"`

	// API versionn.
	Version string `json:"version,omitempty"`
}

// Validate validates this index
func (m *Index) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Index) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Index) UnmarshalBinary(b []byte) error {
	var res Index
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
