// Code generated by go-swagger; DO NOT EDIT.

package index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/5verst/server/models"
)

// IndexOKCode is the HTTP code returned for type IndexOK
const IndexOKCode int = 200

/*IndexOK Success response

swagger:response indexOK
*/
type IndexOK struct {

	/*
	  In: Body
	*/
	Payload *models.Index `json:"body,omitempty"`
}

// NewIndexOK creates IndexOK with default headers values
func NewIndexOK() *IndexOK {

	return &IndexOK{}
}

// WithPayload adds the payload to the index o k response
func (o *IndexOK) WithPayload(payload *models.Index) *IndexOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the index o k response
func (o *IndexOK) SetPayload(payload *models.Index) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IndexOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
